name: fiber-app

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
   
    runs-on: ubuntu-lastest

    steps:
    - uses: action/checkout@v3
    - name: Build and Push image
      run: |
        echo "${{ secrets.DOCKERPW }}" | docker login -u "quaintlotus8443" --password-stdin
        docker image build -t quaintlotus8443/fiber-app:v1
        docker push quaintlotus8443/fiber-app:v1