name: fiber-app

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKERPW }}" | docker login -u "quaintlotus8443" --password-stdin

    - name: Build and Push Docker Image
      run: |
        docker build -t quaintlotus8443/fiber-app:v1 .
        docker push quaintlotus8443/fiber-app:v1
